import React, { useState } from 'react';
import { useTheme } from '../contexts/ThemeContext';

// ─── Theme-aware Color Palettes ───────────────────────────────────────────────

interface ColorPalette {
  bg0: string; bg1: string; bg2: string; bg3: string;
  accent: string; accent2: string;
  red: string; amber: string; cyan: string;
  txt: string; txt2: string; txt3: string;
  border: string; border2: string;
  errBg: string; errBorder: string; errTxt: string;
  fontMono: string; fontBase: string;
}

const TERMINAL: ColorPalette = {
  bg0: '#0d1520', bg1: '#111b2a', bg2: '#152030', bg3: '#1a2840',
  accent: '#2dd4a0', accent2: '#1db88a',
  red: '#e85555', amber: '#e8a030', cyan: '#38c0d4',
  txt: '#e2e8f0', txt2: '#94a3b8', txt3: '#64748b',
  border: '#1e3048', border2: '#253a55',
  errBg: '#200a0a', errBorder: '#4a1010', errTxt: '#f08080',
  fontMono: "'SF Mono','JetBrains Mono',ui-monospace,monospace",
  fontBase: "'SF Mono','JetBrains Mono',ui-monospace,monospace",
};

const BASIC: ColorPalette = {
  bg0: '#0f172a', bg1: '#1e293b', bg2: '#213547', bg3: '#293b55',
  accent: '#b1d0dd', accent2: '#8bb8d0',
  red: '#ef4444', amber: '#f59e0b', cyan: '#06b6d4',
  txt: '#e2e8f0', txt2: '#94a3b8', txt3: '#64748b',
  border: '#334155', border2: '#3d5166',
  errBg: '#1a0505', errBorder: '#3d1010', errTxt: '#fca5a5',
  fontMono: 'ui-monospace, "Cascadia Code", monospace',
  fontBase: 'system-ui, -apple-system, sans-serif',
};

// ─── Types ────────────────────────────────────────────────────────────────────

interface MetaField {
  id: string; name: string; required: boolean; infer: boolean; deletable: boolean;
}
interface Template {
  badge: string; badgeClass: 'test'|'tool'|'attack'; name: string; desc: string; meta: string;
}

// ─── Mock Data ────────────────────────────────────────────────────────────────

const TEMPLATES: Template[] = [
  { badge: '● TEST', badgeClass: 'test', name: 'OWASP LLM Test Suite',
    desc: 'Structured assurance tests targeting OWASP LLM Top 10 risks. Generates reproducible test packages with pass/fail assertions.',
    meta: 'v1.2 · IAC Core' },
  { badge: '● TOOL', badgeClass: 'tool', name: 'Blue Team Scanner',
    desc: 'Network and endpoint discovery tools for cataloging AI service endpoints, request patterns, and model telemetry.',
    meta: 'v1.0 · IAC Core' },
  { badge: '● ATTACK', badgeClass: 'attack', name: 'Red Team Payload Generator',
    desc: 'Offensive extension template for crafting adversarial payloads, flood scenarios, and malformed input attacks.',
    meta: 'v1.1 · IAC Core' },
  { badge: '● TOOL', badgeClass: 'tool', name: 'Monitoring Agent',
    desc: 'Continuous monitoring for model drift, behavioral anomalies, and policy violations in production LLM deployments.',
    meta: 'v0.9 · Community' },
];

const INIT_META_FIELDS: MetaField[] = [
  { id: 'f-name',    name: 'name',      required: true,  infer: true,  deletable: false },
  { id: 'f-version', name: 'version',   required: true,  infer: false, deletable: false },
  { id: 'f-owasp',   name: 'owasp_ref', required: false, infer: true,  deletable: true  },
  { id: 'f-tags',    name: 'tags',      required: false, infer: true,  deletable: true  },
];

const SYSTEM_PROMPT_TEXT =
  `You are a security extension generator for OWASP HACTU8. Generate a {category} extension named "{name}" that targets {owasp_ref}. Follow the HACTU8 extension YAML schema strictly. The extension must be self-contained and repeatable. All test assertions must be deterministic. Return ONLY valid JSON: { "extension_yaml": string, "files": [{path, content}], "readme": string }`;

const PREVIEW_YAML = `# HACTU8 Extension — generated by IAC Workbench
apiVersion: hactu8.owasp.org/v1
kind: Extension
metadata:
  name: llm04-data-poisoning-test
  version: 1.0.0
  category: test
  author: mroxberry
  description: Automated test suite for LLM04:2025
  owasp_ref: LLM04:2025
  tags: [data-poisoning, llm04, test]
spec:
  entrypoint: main.py
  language: python
  template_id: owasp-llm-test-v1.2
  inputs:
    - name: target_endpoint
      type: string
      required: true
  steps:
    - Load poisoning payload corpus
    - Submit adversarial training inputs
    - Evaluate model response drift
    - Generate assurance report`;

const CORRECTION_TEXT = `# Validation errors from iteration 1 — fix these:
ERROR metadata.version: must be semver (e.g. "1.0.0"), got "v1.0"
ERROR spec.entrypoint: "run.py" not in file list; use "main.py"
WARN   metadata.tags: empty array; infer from extension purpose
# Return corrected JSON only. Do not change other fields.`;

// ─── Shared Primitives ────────────────────────────────────────────────────────

const ToggleSwitch: React.FC<{ on: boolean; toggle: () => void; C: ColorPalette }> = ({ on, toggle, C }) => (
  <div onClick={toggle} style={{ position: 'relative', width: 30, height: 16, borderRadius: 8, background: on ? C.accent2 : C.border2, cursor: 'pointer', transition: 'background 0.2s', flexShrink: 0, margin: 'auto' }}>
    <div style={{ position: 'absolute', top: 2, left: on ? 14 : 2, width: 12, height: 12, borderRadius: '50%', background: '#fff', transition: 'left 0.2s', boxShadow: '0 1px 3px rgba(0,0,0,0.4)' }} />
  </div>
);

const Badge: React.FC<{ type: 'test'|'tool'|'attack'; label: string; C: ColorPalette }> = ({ type, label, C }) => {
  const s: Record<string, React.CSSProperties> = {
    test:   { background: `${C.amber}22`, color: C.amber, border: `1px solid ${C.amber}55` },
    tool:   { background: `${C.cyan}22`,  color: C.cyan,  border: `1px solid ${C.cyan}55`  },
    attack: { background: `${C.red}22`,   color: C.red,   border: `1px solid ${C.red}55`   },
  };
  return <div style={{ display: 'inline-flex', alignItems: 'center', gap: 4, padding: '2px 7px', borderRadius: 3, fontSize: 9, fontWeight: 600, marginBottom: 7, letterSpacing: '0.04em', ...s[type] }}>{label}</div>;
};

const Sec: React.FC<{ children: React.ReactNode; C: ColorPalette; style?: React.CSSProperties }> = ({ children, C, style }) => (
  <div style={{ background: C.bg1, border: `1px solid ${C.border}`, borderRadius: 8, padding: 14, marginBottom: 12, ...style }}>{children}</div>
);

const FG: React.FC<{ children: React.ReactNode; grid2?: boolean }> = ({ children, grid2 }) => (
  <div style={grid2 ? { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 } : { marginBottom: 10 }}>{children}</div>
);

const BtnRow: React.FC<{ children: React.ReactNode; C: ColorPalette }> = ({ children, C }) => (
  <div style={{ display: 'flex', alignItems: 'center', gap: 8, justifyContent: 'flex-end', paddingTop: 10, borderTop: `1px solid ${C.border}`, marginTop: 6 }}>{children}</div>
);

interface BtnProps extends React.ButtonHTMLAttributes<HTMLButtonElement> { variant?: 'primary'|'ghost'; C: ColorPalette }
const Btn: React.FC<BtnProps> = ({ variant = 'ghost', C, style, children, ...props }) => (
  <button {...props} style={{ padding: '6px 14px', borderRadius: 5, fontSize: 11, fontFamily: C.fontBase, cursor: 'pointer', fontWeight: 500, transition: 'all 0.15s', border: variant === 'primary' ? 'none' : `1px solid ${C.border2}`, background: variant === 'primary' ? C.accent2 : 'transparent', color: variant === 'primary' ? '#fff' : C.txt2, ...style }}>{children}</button>
);

const Label: React.FC<{ children: React.ReactNode; inferred?: boolean; required?: boolean; C: ColorPalette }> = ({ children, inferred, required, C }) => (
  <div style={{ fontSize: 10, color: C.txt2, marginBottom: 4, display: 'flex', alignItems: 'center', gap: 5, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
    {children}
    {inferred && <span style={{ background: `${C.accent}22`, color: C.accent, fontSize: 9, padding: '1px 5px', borderRadius: 3 }}>inferred</span>}
    {required && <span style={{ color: C.red, fontSize: 9 }}>*</span>}
  </div>
);

const Inp: React.FC<React.InputHTMLAttributes<HTMLInputElement> & { C: ColorPalette; err?: boolean }> = ({ err, C, style, ...props }) => (
  <input {...props} style={{ width: '100%', background: err ? `${C.red}11` : C.bg0, border: `1px solid ${err ? C.red : C.border2}`, borderRadius: 5, padding: '6px 10px', color: C.txt, fontSize: 11, fontFamily: C.fontMono, outline: 'none', boxSizing: 'border-box', ...style }} />
);

const Sel: React.FC<React.SelectHTMLAttributes<HTMLSelectElement> & { C: ColorPalette }> = ({ C, children, style, ...props }) => (
  <select {...props} style={{ width: '100%', background: C.bg0, border: `1px solid ${C.border2}`, borderRadius: 5, padding: '6px 10px', color: C.txt, fontSize: 11, fontFamily: C.fontMono, outline: 'none', boxSizing: 'border-box', ...style }}>{children}</select>
);

const TA: React.FC<React.TextareaHTMLAttributes<HTMLTextAreaElement> & { C: ColorPalette }> = ({ C, style, ...props }) => (
  <textarea {...props} style={{ width: '100%', background: C.bg0, border: `1px solid ${C.border2}`, borderRadius: 5, padding: '6px 10px', color: C.txt, fontSize: 11, fontFamily: C.fontMono, outline: 'none', resize: 'vertical', boxSizing: 'border-box', minHeight: 64, lineHeight: 1.7, ...style }} />
);

// ─── Step Tab ─────────────────────────────────────────────────────────────────

type StepState = 'active'|'done'|'pending';

const StepTab: React.FC<{ label: string; num: number; state: StepState; onClick: () => void; C: ColorPalette }> = ({ label, num, state, onClick, C }) => (
  <div onClick={onClick} style={{ padding: '6px 14px', fontSize: 11, cursor: 'pointer', whiteSpace: 'nowrap', display: 'flex', alignItems: 'center', gap: 5, transition: 'all 0.15s', color: state === 'active' ? C.accent : state === 'done' ? C.txt2 : C.txt3, borderBottom: `2px solid ${state === 'active' ? C.accent : 'transparent'}`, fontFamily: C.fontBase }}>
    <div style={{ width: 16, height: 16, borderRadius: '50%', fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, background: state === 'active' ? C.accent2 : state === 'done' ? `${C.accent}22` : C.bg3, border: `1px solid ${state === 'active' ? C.accent2 : state === 'done' ? C.accent2 : C.border2}`, color: state === 'active' ? '#fff' : state === 'done' ? C.accent : C.txt3 }}>
      {state === 'done' ? '✓' : num}
    </div>
    {label}
  </div>
);

// ─── Builder Screen 0: Template Selection ─────────────────────────────────────

const BS0: React.FC<{ selected: number; setSelected: (n: number) => void; onNext: () => void; C: ColorPalette }> = ({ selected, setSelected, onNext, C }) => (
  <div>
    <h3 style={{ marginBottom: 12, fontSize: 13, fontWeight: 600, fontFamily: C.fontBase }}>Select an Architect Template</h3>
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 16 }}>
      {TEMPLATES.map((t, i) => (
        <div key={i} onClick={() => setSelected(i)} style={{ background: selected === i ? `${C.accent}0d` : C.bg1, border: `1px solid ${selected === i ? C.accent : C.border}`, borderRadius: 8, padding: 12, cursor: 'pointer', transition: 'all 0.15s' }}>
          <Badge type={t.badgeClass} label={t.badge} C={C} />
          <div style={{ fontSize: 12, fontWeight: 600, color: C.txt, marginBottom: 4, fontFamily: C.fontBase }}>{t.name}</div>
          <div style={{ fontSize: 10, color: C.txt2, lineHeight: 1.6 }}>{t.desc}</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 8, fontSize: 9, color: C.txt3 }}>
            <span>{t.meta}</span>
            {selected === i && <span style={{ marginLeft: 'auto', color: C.accent }}>✓ Selected</span>}
          </div>
        </div>
      ))}
    </div>
    <Btn variant="primary" C={C} onClick={onNext}>Use Template →</Btn>
  </div>
);

// ─── Builder Screen 1: Prompt & Metadata ──────────────────────────────────────

const BS1: React.FC<{ onBack: () => void; onNext: () => void; C: ColorPalette }> = ({ onBack, onNext, C }) => (
  <div>
    <FG>
      <Label C={C}>Describe the extension</Label>
      <TA C={C} placeholder={'Create a test suite extension for LLM04:2025 Data and Model Poisoning\n\ne.g. "Create a tool extension to crawl the network and find AI requests, name it IntelMap"  ·  ⌘↩ to generate'} style={{ minHeight: 96 }} />
      <div style={{ fontSize: 10, color: C.txt3, marginTop: 5, lineHeight: 1.5 }}>⚡ Fields marked <span style={{ background: `${C.accent}22`, color: C.accent, fontSize: 9, padding: '1px 5px', borderRadius: 3 }}>inferred</span> were extracted from your prompt — review before generating.</div>
    </FG>
    <Sec C={C}>
      <div style={{ fontSize: 9, fontWeight: 600, color: C.txt2, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 10 }}>Extension Metadata</div>
      <FG><Label C={C} inferred required>Name</Label><Inp C={C} defaultValue="llm04-data-poisoning-test" /></FG>
      <FG grid2>
        <FG><Label C={C} required>Version</Label><Inp C={C} defaultValue="1.0.0" /></FG>
        <FG><Label C={C} required>Category</Label><Sel C={C}><option>test</option><option>tool</option><option>attack</option></Sel></FG>
      </FG>
      <FG><Label C={C} required>Author</Label><Inp C={C} defaultValue="mroxberry" /></FG>
      <FG><Label C={C} required>Description</Label><TA C={C} defaultValue="Automated test suite targeting LLM04:2025 Data and Model Poisoning. Evaluates model responses to known poisoning patterns." style={{ minHeight: 48 }} /></FG>
      <FG grid2>
        <FG><Label C={C} inferred>OWASP Reference</Label><Inp C={C} defaultValue="LLM04:2025" /></FG>
        <FG><Label C={C} inferred>Tags</Label><Inp C={C} defaultValue="data-poisoning, llm04, test" /></FG>
      </FG>
    </Sec>
    <BtnRow C={C}><Btn C={C} onClick={onBack}>← Back</Btn><Btn variant="primary" C={C} onClick={onNext}>Generate Extension →</Btn></BtnRow>
  </div>
);

// ─── Builder Screen 2: Generating ─────────────────────────────────────────────

const BS2: React.FC<{ onCancel: () => void; onNext: () => void; C: ColorPalette }> = ({ onCancel, onNext, C }) => (
  <div>
    <div style={{ background: `${C.amber}10`, border: `1px solid ${C.amber}44`, borderRadius: 7, padding: '10px 14px', marginBottom: 12, display: 'flex', alignItems: 'center', gap: 10 }}>
      <div style={{ width: 26, height: 26, borderRadius: '50%', background: `${C.amber}22`, border: `1px solid ${C.amber}66`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, flexShrink: 0 }}>⚡</div>
      <div style={{ fontSize: 11, fontWeight: 600, fontFamily: C.fontBase }}>Generating via <strong>claude-sonnet-4</strong> · Anthropic</div>
      <div style={{ display: 'flex', gap: 4, marginLeft: 'auto' }}>
        {[0,1,2].map(i => <div key={i} style={{ width: 8, height: 8, borderRadius: '50%', background: i === 0 ? C.accent : i === 1 ? C.amber : C.bg3, border: `1px solid ${i === 0 ? C.accent2 : i === 1 ? C.amber : C.border2}`, animation: i === 1 ? 'wb-blink 1s ease-in-out infinite' : 'none' }} />)}
      </div>
      <div style={{ marginLeft: 10, fontSize: 10, color: C.txt3 }}>Iteration 1 / 3</div>
    </div>
    <div style={{ display: 'flex', gap: 6, marginBottom: 12 }}>
      {[{l:'Step',v:'▶ Generating',a:true},{l:'Validating',v:'Waiting…',a:false},{l:'Correcting',v:'Waiting…',a:false}].map((s,i) => (
        <div key={i} style={{ flex: 1, background: C.bg1, border: `1px solid ${C.border}`, borderRadius: 6, padding: '8px 10px' }}>
          <div style={{ fontSize: 9, color: C.txt3, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 3 }}>{s.l}</div>
          <div style={{ fontSize: 11, color: s.a ? C.accent : C.txt3 }}>{s.v}</div>
        </div>
      ))}
    </div>
    <div style={{ marginBottom: 12 }}>
      <div style={{ fontSize: 10, color: C.txt2, marginBottom: 6, fontWeight: 600 }}>LLM Output Stream</div>
      <div style={{ background: C.bg0, border: `1px solid ${C.border}`, borderRadius: 7, padding: 12, fontFamily: 'monospace', fontSize: 10, color: C.txt2, lineHeight: 1.9, height: 180, overflowY: 'auto' }}>
        <span style={{ color: C.cyan }}>extension_yaml</span><span style={{ color: C.amber }}>: </span><span style={{ color: C.accent }}>|</span><br />
        <span style={{ color: C.cyan }}>{'  apiVersion'}</span><span style={{ color: C.amber }}>: </span><span style={{ color: C.accent }}>hactu8.owasp.org/v1</span><br />
        <span style={{ color: C.cyan }}>{'  kind'}</span><span style={{ color: C.amber }}>: </span><span style={{ color: C.accent }}>Extension</span><br />
        <span style={{ color: C.cyan }}>{'  metadata'}</span><span style={{ color: C.amber }}>:</span><br />
        <span style={{ color: C.cyan }}>{'    name'}</span><span style={{ color: C.amber }}>: </span><span style={{ color: C.accent }}>llm04-data-poisoning-test</span><br />
        <span style={{ color: C.cyan }}>{'    version'}</span><span style={{ color: C.amber }}>: </span><span style={{ color: C.accent }}>1.0.0</span><br />
        <span style={{ color: C.cyan }}>{'    owasp_ref'}</span><span style={{ color: C.amber }}>: </span><span style={{ color: C.accent }}>LLM04:2025</span><br />
        <span style={{ color: C.cyan }}>{'  spec'}</span><span style={{ color: C.amber }}>:</span><br />
        <span style={{ color: C.cyan }}>{'    entrypoint'}</span><span style={{ color: C.amber }}>: </span><span style={{ color: C.accent }}>main.py</span><br />
        <span style={{ color: C.cyan }}>{'    steps'}</span><span style={{ color: C.amber }}>:</span><br />
        <span style={{ color: C.cyan }}>{'      -'}</span> <span style={{ color: C.accent }}>Load poisoning payload corpus</span><br />
        <span style={{ color: C.cyan }}>{'      -'}</span> <span style={{ color: C.accent }}>Submit adversarial training inputs</span>
        <span style={{ display: 'inline-block', width: 6, height: 12, background: C.accent, verticalAlign: 'middle', animation: 'wb-cursor 0.7s step-end infinite' }} />
      </div>
    </div>
    <div style={{ marginBottom: 12 }}>
      <div style={{ fontSize: 10, color: C.txt2, marginBottom: 6, fontWeight: 600 }}>Artifacts</div>
      <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
        {[{n:'extension.yaml',d:true},{n:'main.py',d:false},{n:'README.md',d:false}].map(a => (
          <div key={a.n} style={{ display: 'flex', alignItems: 'center', gap: 5, background: C.bg1, border: `1px solid ${C.border}`, borderRadius: 5, padding: '4px 10px', fontSize: 10, fontFamily: C.fontMono }}>
            <span style={{ color: a.d ? C.accent : C.txt3 }}>{a.d ? '●' : '◌'}</span>{a.n}
          </div>
        ))}
      </div>
    </div>
    <BtnRow C={C}><Btn C={C} onClick={onCancel}>Cancel</Btn><Btn variant="primary" C={C} onClick={onNext}>View Results →</Btn></BtnRow>
  </div>
);

// ─── Builder Screen 3: Preview & Publish ──────────────────────────────────────

const BS3: React.FC<{ onBack: () => void; C: ColorPalette }> = ({ onBack, C }) => (
  <div>
    <div style={{ marginBottom: 18 }}>
      <div style={{ fontSize: 12, fontWeight: 600, marginBottom: 8, fontFamily: C.fontBase }}>extension.yaml</div>
      <div style={{ background: C.bg0, border: `1px solid ${C.border}`, borderRadius: 6, padding: '10px 12px', fontFamily: 'monospace', fontSize: 9, color: C.txt2, lineHeight: 1.9, whiteSpace: 'pre' }}>{PREVIEW_YAML}</div>
    </div>
    <div style={{ background: C.bg1, border: `1px solid ${C.border}`, borderRadius: 7, padding: 10, marginBottom: 10 }}>
      <div style={{ fontSize: 10, fontWeight: 600, marginBottom: 8, color: C.accent }}>Validation</div>
      {['Schema validation','Name format','Version semver','Category valid','Entrypoint exists','OWASP ref format'].map(r => (
        <div key={r} style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '3px 0', fontSize: 10, color: C.txt2, borderBottom: `1px solid ${C.border}` }}>
          <span style={{ color: C.accent, fontSize: 9, fontWeight: 600, width: 40, flexShrink: 0 }}>✓ PASS</span>{r}
        </div>
      ))}
    </div>
    <div style={{ background: C.bg1, border: `1px solid ${C.border}`, borderRadius: 7, padding: '8px 12px', marginBottom: 10 }}>
      <div style={{ fontSize: 10, fontWeight: 600, marginBottom: 8 }}>Generated Files</div>
      {[['📄','extension.yaml'],['🐍','main.py'],['📝','README.md']].map(([ic,n]) => (
        <div key={n} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '3px 0', fontSize: 10, color: C.txt2, cursor: 'pointer' }}>{ic} {n}</div>
      ))}
    </div>
    <div style={{ background: `${C.accent}0d`, border: `1px solid ${C.accent}33`, borderRadius: 6, padding: 10, marginBottom: 12, textAlign: 'center' }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: C.accent, marginBottom: 6 }}>All checks passed</div>
      <div style={{ fontSize: 13, fontWeight: 600 }}>6 / 6 validations</div>
    </div>
    <BtnRow C={C}><Btn C={C} onClick={onBack}>← Edit Metadata</Btn><Btn C={C}>⬇ Export .zip</Btn><Btn variant="primary" C={C}>Publish to Registry →</Btn></BtnRow>
  </div>
);

// ─── Architect Screen 0: Template Editor ──────────────────────────────────────

const AS0: React.FC<{
  fields: MetaField[]; onToggleRequired: (id: string) => void; onToggleInfer: (id: string) => void;
  onRemove: (id: string) => void; onAdd: () => void;
  sysPrompt: string; setSysPrompt: (v: string) => void; C: ColorPalette;
}> = ({ fields, onToggleRequired, onToggleInfer, onRemove, onAdd, sysPrompt, setSysPrompt, C }) => (
  <div>
    <div style={{ marginBottom: 18 }}>
      <h3 style={{ marginBottom: 12, fontSize: 13, fontWeight: 600, fontFamily: C.fontBase }}>Template Identity</h3>
      <Sec C={C}>
        <FG><Label C={C} required>Template Name</Label><Inp C={C} placeholder="e.g., OWASP LLM Test Suite" /></FG>
        <FG grid2>
          <FG><Label C={C} required>Version</Label><Inp C={C} placeholder="1.0.0" /></FG>
          <FG><Label C={C} required>Extension Category</Label><Sel C={C}><option>test</option><option>tool</option><option>attack</option></Sel></FG>
        </FG>
        <FG><Label C={C}>Author</Label><Inp C={C} /></FG>
        <FG><Label C={C}>Description</Label><TA C={C} defaultValue="Structured assurance tests targeting OWASP LLM Top 10 risks. Generates reproducible test packages." style={{ minHeight: 48 }} /></FG>
      </Sec>
    </div>

    <div style={{ marginBottom: 18 }}>
      <h3 style={{ marginBottom: 12, fontSize: 13, fontWeight: 600, fontFamily: C.fontBase }}>Metadata Field Rules</h3>
      <Sec C={C}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 70px 90px 24px', gap: 6, marginBottom: 6, paddingBottom: 6, borderBottom: `1px solid ${C.border}` }}>
          {['Field','Required','Infer from prompt',''].map((h, i) => (
            <div key={i} style={{ fontSize: 9, color: C.txt3, textAlign: i === 0 ? 'left' : 'center', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{h}</div>
          ))}
        </div>
        {fields.map(f => (
          <div key={f.id} style={{ display: 'grid', gridTemplateColumns: '1fr 70px 90px 24px', gap: 6, alignItems: 'center', background: C.bg0, border: `1px solid ${C.border}`, borderRadius: 5, padding: '7px 10px', marginBottom: 5, fontSize: 11 }}>
            <span style={{ fontFamily: 'monospace' }}>{f.name}</span>
            <div style={{ display: 'flex', justifyContent: 'center' }}><ToggleSwitch on={f.required} toggle={() => onToggleRequired(f.id)} C={C} /></div>
            <div style={{ display: 'flex', justifyContent: 'center' }}><ToggleSwitch on={f.infer} toggle={() => onToggleInfer(f.id)} C={C} /></div>
            <div style={{ display: 'flex', justifyContent: 'center' }}>
              {f.deletable && <button onClick={() => onRemove(f.id)} style={{ width: 20, height: 20, borderRadius: 3, background: 'transparent', border: `1px solid ${C.red}44`, color: C.red, fontSize: 11, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: C.fontBase }}>×</button>}
            </div>
          </div>
        ))}
        <div onClick={onAdd} style={{ fontSize: 10, color: C.accent, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 3, padding: '4px 0' }}>+ Add custom field</div>
      </Sec>
    </div>

    <div style={{ marginBottom: 18 }}>
      <h3 style={{ marginBottom: 12, fontSize: 13, fontWeight: 600, fontFamily: C.fontBase }}>System Prompt</h3>
      <div style={{ background: C.bg1, border: `1px solid ${C.border2}`, borderRadius: 8, padding: 12 }}>
        <div style={{ fontSize: 9, color: C.txt3, marginBottom: 6 }}>Injected as LLM system context during generation. Use <span style={{ color: C.accent }}>{'{variable}'}</span> tokens for dynamic substitution.</div>
        <div style={{ background: C.bg0, border: `1px solid ${C.border}`, borderRadius: 4, padding: 8, marginBottom: 8, fontSize: 10, color: C.txt2 }}>
          system_prompt.txt <span style={{ fontSize: 9, marginLeft: 8, color: C.txt3 }}>tokens: {'{category}'}, {'{name}'}, {'{owasp_ref}'}</span>
        </div>
        <div style={{ background: C.bg0, border: `1px solid ${C.border2}`, borderRadius: 7, overflow: 'hidden' }}>
          <div style={{ background: C.bg1, borderBottom: `1px solid ${C.border}`, padding: '6px 12px', fontSize: 9, color: C.txt3, textTransform: 'uppercase', letterSpacing: '0.06em' }}>System Prompt ({sysPrompt.length} chars)</div>
          <textarea value={sysPrompt} onChange={e => setSysPrompt(e.target.value)} style={{ width: '100%', background: 'transparent', border: 'none', padding: '10px 12px', color: C.txt2, fontSize: 10, lineHeight: 1.9, resize: 'none', fontFamily: 'monospace', outline: 'none', minHeight: 90, boxSizing: 'border-box' }} />
        </div>
      </div>
    </div>

    <div style={{ marginBottom: 18 }}>
      <h3 style={{ marginBottom: 12, fontSize: 13, fontWeight: 600, fontFamily: C.fontBase }}>Output Contract</h3>
      <div style={{ background: C.bg1, border: `1px solid ${C.border2}`, borderRadius: 8, padding: 12 }}>
        <div style={{ fontSize: 9, color: C.txt2, marginBottom: 10 }}>Files the LLM must produce. Missing required files = validation failure.</div>
        {[['extension.yaml','required'],['main.py','required'],['README.md','required']].map(([name, tag]) => (
          <div key={name} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '5px 0', borderBottom: `1px solid ${C.border}`, fontSize: 10, color: C.txt2 }}>
            <span style={{ color: C.accent, fontSize: 9 }}>✓</span>
            <span style={{ fontFamily: C.fontMono }}>{name}</span>
            <span style={{ marginLeft: 'auto', fontSize: 9, color: C.txt3 }}>{tag}</span>
          </div>
        ))}
        <div style={{ marginTop: 10, paddingTop: 10, borderTop: `1px solid ${C.border}`, fontSize: 9, color: C.txt3 }}>
          Validates against schema: <span style={{ color: C.txt2, fontFamily: C.fontMono }}>hactu8-extension-schema-v1</span>
        </div>
      </div>
    </div>

    <div style={{ marginBottom: 18 }}>
      <h3 style={{ marginBottom: 12, fontSize: 13, fontWeight: 600, fontFamily: C.fontBase }}>Scaffold Stub</h3>
      <div style={{ background: C.bg1, border: `1px solid ${C.border2}`, borderRadius: 8, padding: 12 }}>
        <div style={{ fontSize: 9, color: C.txt2, marginBottom: 10 }}>Starter code injected into the generation context. LLM fills the implementation.</div>
        <div style={{ background: C.bg0, border: `1px solid ${C.border}`, borderRadius: 7, overflow: 'hidden' }}>
          <div style={{ background: C.bg1, borderBottom: `1px solid ${C.border}`, padding: '5px 12px', fontSize: 9, color: C.txt3, display: 'flex', justifyContent: 'space-between' }}>
            <span style={{ fontFamily: C.fontMono }}>main.py</span>
            <button style={{ background: C.bg2, border: `1px solid ${C.border2}`, borderRadius: 3, padding: '2px 7px', fontSize: 9, color: C.txt2, cursor: 'pointer', fontFamily: C.fontBase }}>Format</button>
          </div>
          <div style={{ padding: '10px 12px', fontFamily: 'monospace', fontSize: 10, lineHeight: 1.9, color: C.txt2, maxHeight: 140, overflowY: 'auto' }}>
            {[['1','# HACTU8 Extension Stub — {name}'],['2','# Category: {category} | OWASP: {owasp_ref}'],['3',''],['4','from hactu8.sdk import Extension, TestResult'],['5',''],['6','class {ClassName}(Extension):'],['7','    def run(self, inputs) -> TestResult:'],['8','        # TODO: implement'],['9','        raise NotImplementedError']].map(([n, line]) => (
              <div key={n} style={{ display: 'flex', gap: 12 }}>
                <span style={{ color: C.txt3, width: 12, textAlign: 'right', flexShrink: 0, fontSize: 9 }}>{n}</span>
                <span>{line}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>

    <BtnRow C={C}><Btn C={C}>Discard</Btn><Btn C={C}>Save Draft</Btn><Btn variant="primary" C={C}>Publish Template →</Btn></BtnRow>
  </div>
);

// ─── Architect Screen 1: Validation Failure ───────────────────────────────────

const AS1: React.FC<{ onBack: () => void; C: ColorPalette }> = ({ onBack, C }) => (
  <div>
    <div style={{ background: C.errBg, border: `1px solid ${C.errBorder}`, borderRadius: 7, padding: 12, marginBottom: 12 }}>
      <div style={{ fontSize: 10, fontWeight: 600, color: C.errTxt, marginBottom: 10, letterSpacing: '0.04em' }}>⚠ Schema validation failed — auto-correcting</div>
      <div style={{ fontSize: 9, color: C.txt2, marginBottom: 10 }}>LLM receives error context and retries. Max 3 iterations.</div>
      {[
        { kind: 'ERROR', loc: 'line 6 · metadata.version', msg: 'Invalid semver. Got "v1.0" — expected "1.0.0"', fix: '↳ Apply fix: replace with "1.0.0"' },
        { kind: 'ERROR', loc: 'line 14 · spec.entrypoint', msg: 'Entrypoint "run.py" not in file list. Available: main.py', fix: '↳ Apply fix: change to "main.py"' },
        { kind: 'WARN',  loc: 'line 9 · metadata.tags', msg: 'Field tags is empty — recommended for registry discoverability.', fix: '↳ Infer tags from prompt context' },
      ].map((e, i) => (
        <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, padding: '7px 0', borderBottom: i < 2 ? `1px solid ${C.errBorder}` : 'none', fontSize: 10 }}>
          <span style={{ flexShrink: 0, padding: '2px 6px', borderRadius: 3, fontSize: 9, fontWeight: 600, background: e.kind === 'ERROR' ? `${C.red}22` : `${C.amber}22`, color: e.kind === 'ERROR' ? C.red : C.amber, border: `1px solid ${e.kind === 'ERROR' ? `${C.red}55` : `${C.amber}55`}` }}>{e.kind}</span>
          <div>
            <div style={{ color: C.txt3, fontFamily: 'monospace', fontSize: 9 }}>{e.loc}</div>
            <div style={{ color: C.txt2, lineHeight: 1.5, marginTop: 2 }}>{e.msg}</div>
            <div style={{ marginTop: 4, fontSize: 9, color: C.accent, cursor: 'pointer' }}>{e.fix}</div>
          </div>
        </div>
      ))}
    </div>

    <div style={{ marginBottom: 18 }}>
      <div style={{ fontSize: 12, fontWeight: 600, marginBottom: 8, fontFamily: C.fontBase }}>extension.yaml — inline diagnostics</div>
      <div style={{ background: C.bg0, border: `1px solid ${C.border}`, borderRadius: 6, padding: '10px 12px', fontFamily: 'monospace', fontSize: 9, color: C.txt, lineHeight: 1.7 }}>
        {[
          { n: 1,  text: 'apiVersion: hactu8.owasp.org/v1' },
          { n: 2,  text: 'kind: Extension' },
          { n: 3,  text: 'metadata:' },
          { n: 4,  text: '  name: llm04-data-poisoning-test' },
          { n: 5,  text: '  category: test' },
          { n: 6,  text: '  version: "v1.0"', errMark: '✕ invalid semver', isErr: true },
          { n: 7,  text: '  author: mroxberry' },
          { n: 8,  text: '  description: Automated test suite for LLM04:2025' },
          { n: 9,  text: '  tags: []', warnMark: '⚠ empty — add tags', isWarn: true },
          { n: 10, text: '  owasp_ref: LLM04:2025' },
          { n: 11, text: 'spec:' },
          { n: 12, text: '  language: python' },
          { n: 13, text: '  template_id: owasp-llm-test-v1.2' },
          { n: 14, text: '  entrypoint: "run.py"', errMark: '✕ file not found', isErr: true },
          { n: 15, text: '  inputs:' },
          { n: 16, text: '    - name: target_endpoint' },
          { n: 17, text: '      type: string' },
          { n: 18, text: '      required: true' },
        ].map(row => (
          <div key={row.n} style={{ display: 'flex', gap: 6, background: row.isErr ? `${C.red}14` : row.isWarn ? `${C.amber}14` : 'transparent', borderRadius: 2, padding: '0 2px' }}>
            <span style={{ width: 22, textAlign: 'right', color: row.isErr ? C.red : C.txt3, flexShrink: 0, fontSize: 9 }}>{row.n}</span>
            <span style={{ flex: 1 }}>
              <span style={{ borderBottom: row.isErr ? `2px dashed ${C.red}` : row.isWarn ? `2px dashed ${C.amber}` : 'none' }}>{row.text}</span>
              {row.errMark && <span style={{ fontSize: 9, color: C.red, marginLeft: 8 }}>{row.errMark}</span>}
              {row.warnMark && <span style={{ fontSize: 9, color: C.amber, marginLeft: 8 }}>{row.warnMark}</span>}
            </span>
          </div>
        ))}
      </div>
    </div>

    <div style={{ marginBottom: 18, background: C.bg1, border: `1px solid ${C.border}`, borderRadius: 7, padding: 12 }}>
      <div style={{ fontSize: 10, color: C.txt2, marginBottom: 10, fontWeight: 600 }}>Correction context → LLM (iteration 2)</div>
      <div style={{ background: C.bg0, border: `1px solid ${C.border}`, borderRadius: 6, padding: '10px 12px', fontFamily: 'monospace', fontSize: 9, color: C.txt2, lineHeight: 1.9, whiteSpace: 'pre' }}>{CORRECTION_TEXT}</div>
    </div>

    <BtnRow C={C}><Btn C={C} onClick={onBack}>← Back to Editor</Btn><Btn C={C}>Apply All Fixes</Btn><Btn C={C}>Manually Retry Generation →</Btn></BtnRow>
  </div>
);

// ─── Workbench Root ───────────────────────────────────────────────────────────

const BUILDER_STEPS = ['Template', 'Prompt & Metadata', 'Generating', 'Preview & Publish'];
const ARCH_STEPS    = ['Template Editor', 'Validation Failure'];

const Workbench: React.FC = () => {
  const { theme } = useTheme();
  const C = theme === 'terminal' ? TERMINAL : BASIC;

  const [mode, setMode]               = useState<'builder'|'architect'>('builder');
  const [builderStep, setBuilderStep] = useState(0);
  const [archStep, setArchStep]       = useState(0);
  const [selectedTemplate, setSelectedTemplate] = useState(0);
  const [metaFields, setMetaFields]   = useState<MetaField[]>(INIT_META_FIELDS);
  const [sysPrompt, setSysPrompt]     = useState(SYSTEM_PROMPT_TEXT);

  const toggleRequired = (id: string) => setMetaFields(p => p.map(f => f.id === id ? { ...f, required: !f.required } : f));
  const toggleInfer    = (id: string) => setMetaFields(p => p.map(f => f.id === id ? { ...f, infer: !f.infer } : f));
  const removeField    = (id: string) => setMetaFields(p => p.filter(f => f.id !== id));
  const addField       = () => {
    const n = metaFields.filter(f => f.deletable).length + 1;
    setMetaFields(p => [...p, { id: `f-custom-${Date.now()}`, name: `custom_field_${n}`, required: false, infer: false, deletable: true }]);
  };

  return (
    <>
      <style>{`@keyframes wb-blink{0%,100%{opacity:1}50%{opacity:.3}}@keyframes wb-cursor{0%,100%{opacity:1}50%{opacity:0}}`}</style>
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden', background: C.bg0, color: C.txt, fontFamily: C.fontBase, fontSize: 13 }}>

        {/* Header */}
        <div style={{ borderBottom: `1px solid ${C.border}`, padding: '0 20px', flexShrink: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 0 0' }}>
            <div style={{ fontSize: 15, fontWeight: 600, letterSpacing: '0.01em' }}>Workbench</div>
            <div style={{ display: 'flex', background: C.bg1, border: `1px solid ${C.border}`, borderRadius: 6, overflow: 'hidden' }}>
              {(['builder','architect'] as const).map((m, i) => (
                <button key={m} onClick={() => setMode(m)} style={{ padding: '4px 12px', fontSize: 11, cursor: 'pointer', fontFamily: C.fontBase, border: 'none', transition: 'all 0.15s', background: mode === m ? C.bg3 : 'transparent', color: mode === m ? C.accent : C.txt3 }}>
                  {i === 0 ? 'Builder' : 'Architect'}
                </button>
              ))}
            </div>
          </div>
          <div style={{ display: 'flex', paddingTop: 10 }}>
            {(mode === 'builder' ? BUILDER_STEPS : ARCH_STEPS).map((label, i) => {
              const step = mode === 'builder' ? builderStep : archStep;
              const setStep = mode === 'builder' ? setBuilderStep : setArchStep;
              return <StepTab key={i} label={label} num={i+1} C={C} onClick={() => setStep(i)} state={step === i ? 'active' : step > i ? 'done' : 'pending'} />;
            })}
          </div>
        </div>

        {/* Scrollable body */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '18px 20px' }}>
          {mode === 'builder' && builderStep === 0 && <BS0 selected={selectedTemplate} setSelected={setSelectedTemplate} onNext={() => setBuilderStep(1)} C={C} />}
          {mode === 'builder' && builderStep === 1 && <BS1 onBack={() => setBuilderStep(0)} onNext={() => setBuilderStep(2)} C={C} />}
          {mode === 'builder' && builderStep === 2 && <BS2 onCancel={() => setBuilderStep(1)} onNext={() => setBuilderStep(3)} C={C} />}
          {mode === 'builder' && builderStep === 3 && <BS3 onBack={() => setBuilderStep(1)} C={C} />}
          {mode === 'architect' && archStep === 0 && <AS0 fields={metaFields} onToggleRequired={toggleRequired} onToggleInfer={toggleInfer} onRemove={removeField} onAdd={addField} sysPrompt={sysPrompt} setSysPrompt={setSysPrompt} C={C} />}
          {mode === 'architect' && archStep === 1 && <AS1 onBack={() => setArchStep(0)} C={C} />}
        </div>
      </div>
    </>
  );
};

export default Workbench;
